version: "2"
services:
  dev:
    image: python:2
    command: bash
    working_dir: /code/
    ports:
      - 8000
    volumes:
      - ./:/code/

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350
